import type { Participant } from "../types";

export const FLAG_LABELS = [
  "PK",
  "DISC",
  "EAS4",
  "EAS5",
  "EAS6",
  "EAS7",
  "EAS10",
  "A5",
  "DR",
  "DA5",
  "ST7",
  "Intray1",
  "Intray2",
] as const;

export const DUMMY_PARTICIPANTS: Participant[] = [
  {
    id: "P-001",
    name: "Alea Thorne",
    testNumber: "10/13",
    date: "Feb 10, 2026",
    flags: [
      true,
      true,
      false,
      true,
      true,
      false,
      false,
      true,
      true,
      true,
      false,
    ],
  },
  {
    id: "P-002",
    name: "Noah Patel",
    testNumber: "7/13",
    date: "Feb 09, 2026",
    flags: [
      true,
      false,
      true,
      false,
      true,
      false,
      true,
      false,
      false,
      true,
      false,
    ],
  },
  {
    id: "P-003",
    name: "Lina Watanabe",
    testNumber: "12/13",
    date: "Feb 08, 2026",
    flags: [true, true, true, true, true, true, true, true, true, false, true],
  },
  {
    id: "P-004",
    name: "Marco Silva",
    testNumber: "5/13",
    date: "Feb 07, 2026",
    flags: [
      false,
      true,
      true,
      false,
      true,
      false,
      false,
      false,
      true,
      false,
      false,
    ],
  },
  {
    id: "P-005",
    name: "Evelyn Cole",
    testNumber: "9/13",
    date: "Feb 06, 2026",
    flags: [
      true,
      true,
      true,
      false,
      true,
      true,
      false,
      true,
      false,
      true,
      false,
    ],
  },
  {
    id: "P-006",
    name: "Rafi Idris",
    testNumber: "3/13",
    date: "Feb 05, 2026",
    flags: [
      false,
      false,
      false,
      true,
      false,
      false,
      false,
      false,
      false,
      true,
      false,
    ],
  },
];
