export const FLAG_LABELS = [
  { label: "PK", value: "papikostick" },
  { label: "DISC", value: "disc" },
  { label: "EAS4", value: "eas4" },
  { label: "EAS5", value: "eas5" },
  { label: "EAS6", value: "eas6" },
  { label: "EAS7", value: "eas7" },
  { label: "EAS10", value: "eas10" },
  { label: "A5", value: "a5" },
  { label: "DR", value: "dr" },
  { label: "DA5", value: "da5" },
  { label: "ST7", value: "st7" },
  { label: "Intray1", value: "intray1" },
  { label: "Intray2", value: "intray2" },
] as const;

export const DUMMY_PARTICIPANTS: any = [
  {
    id: "P-001",
    name: "Alea Thorne",
    testNumber: "10/13",
    date: "Feb 10, 2026",
    flags: [
      true,
      true,
      false,
      true,
      true,
      false,
      false,
      true,
      true,
      true,
      false,
    ],
  },
  {
    id: "P-002",
    name: "Noah Patel",
    testNumber: "7/13",
    date: "Feb 09, 2026",
    flags: [
      true,
      false,
      true,
      false,
      true,
      false,
      true,
      false,
      false,
      true,
      false,
    ],
  },
  {
    id: "P-003",
    name: "Lina Watanabe",
    testNumber: "12/13",
    date: "Feb 08, 2026",
    flags: [true, true, true, true, true, true, true, true, true, false, true],
  },
  {
    id: "P-004",
    name: "Marco Silva",
    testNumber: "5/13",
    date: "Feb 07, 2026",
    flags: [
      false,
      true,
      true,
      false,
      true,
      false,
      false,
      false,
      true,
      false,
      false,
    ],
  },
  {
    id: "P-005",
    name: "Evelyn Cole",
    testNumber: "9/13",
    date: "Feb 06, 2026",
    flags: [
      true,
      true,
      true,
      false,
      true,
      true,
      false,
      true,
      false,
      true,
      false,
    ],
  },
  {
    id: "P-006",
    name: "Rafi Idris",
    testNumber: "3/13",
    date: "Feb 05, 2026",
    flags: [
      false,
      false,
      false,
      true,
      false,
      false,
      false,
      false,
      false,
      true,
      false,
    ],
  },
];
